import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001a42",
        "inverse-surface": "#dae2fd",
        "primary-fixed-dim": "#adc6ff",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "secondary": "#b7c8e1",
        "on-primary": "#002e6a",
        "surface": "#0b1326",
        "on-primary-fixed-variant": "#004395",
        "tertiary-container": "#df7412",
        "on-tertiary-fixed": "#311400",
        "tertiary-fixed-dim": "#ffb786",
        "secondary-fixed": "#d3e4fe",
        "surface-bright": "#31394d",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#38485d",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#461f00",
        "outline-variant": "#424754",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#131b2e",
        "surface-container-highest": "#2d3449",
        "on-secondary-container": "#a9bad3",
        "outline": "#8c909f",
        "on-surface-variant": "#c2c6d6",
        "tertiary": "#ffb786",
        "secondary-container": "#3a4a5f",
        "inverse-primary": "#005ac2",
        "on-primary-container": "#00285d",
        "on-surface": "#dae2fd",
        "on-tertiary": "#502400",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed": "#0b1c30",
        "on-background": "#dae2fd",
        "surface-tint": "#adc6ff",
        "surface-container-lowest": "#060e20",
        "primary": "#adc6ff",
        "surface-container-high": "#222a3d",
        "on-error": "#690005",
        "inverse-on-surface": "#283044",
        "background": "#020617", // Set to matching dark space background #020617
        "surface-dim": "#0b1326",
        "on-secondary": "#213145",
        "tertiary-fixed": "#ffdcc6",
        "primary-container": "#4d8eff",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#723600",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "lg": "24px",
        "3xl": "64px",
        "base": "4px",
        "md": "16px",
        "2xl": "48px",
        "sm": "8px",
        "xl": "32px",
        "xs": "4px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "mono-md": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;
