import argparse
import sys
import datetime

def generate_yara_rule(name, description, author, strings, condition):
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    
    rule = f'rule {name} {{\n'
    rule += '    meta:\n'
    rule += f'        description = "{description}"\n'
    rule += f'        author = "{author}"\n'
    rule += f'        date = "{date_str}"\n'
    
    if strings:
        rule += '    strings:\n'
        for i, s in enumerate(strings):
            # If string contains space and hex characters, assume hex pattern if requested, but for simplicity treat as string or hex based on input
            if s.startswith('{') and s.endswith('}'):
                rule += f'        $s{i} = {s}\n'
            else:
                rule += f'        $s{i} = "{s}"\n'
                
    rule += '    condition:\n'
    if condition:
        rule += f'        {condition}\n'
    elif strings:
        rule += '        any of them\n'
    else:
        rule += '        true\n'
        
    rule += '}\n'
    return rule

def main():
    parser = argparse.ArgumentParser(description="Standalone YARA Rule Generator")
    parser.add_argument("name", help="Name of the YARA rule (alphanumeric and underscores only)")
    parser.add_argument("-d", "--description", default="Generated by ThreatMap YARA Generator", help="Description of the rule")
    parser.add_argument("-a", "--author", default="ThreatMap User", help="Author of the rule")
    parser.add_argument("-s", "--strings", nargs='+', default=[], help="Strings to match. Use { 01 23 45 } for hex strings.")
    parser.add_argument("-c", "--condition", help="Condition for the rule (default: 'any of them' if strings provided, else 'true')")
    parser.add_argument("-o", "--output", help="Output file to write the rule to. Prints to stdout if not specified.")
    
    args = parser.parse_args()
    
    # Validation for rule name
    if not args.name.isidentifier():
        print("Error: Rule name must be a valid identifier (alphanumeric and underscores only, cannot start with a number).")
        sys.exit(1)
        
    rule_content = generate_yara_rule(args.name, args.description, args.author, args.strings, args.condition)
    
    if args.output:
        try:
            with open(args.output, 'w') as f:
                f.write(rule_content)
            print(f"Successfully wrote YARA rule to {args.output}")
        except Exception as e:
            print(f"Error writing to file: {e}")
            sys.exit(1)
    else:
        print("\n--- Generated YARA Rule ---\n")
        print(rule_content)

if __name__ == "__main__":
    main()
